# Generated by Django 5.0 on 2024-01-05 05:58

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='article/avatars/default.jpg', upload_to='article/avatars/%Y%m%d/'),
        ),
    ]
